Diabetes_Prediction
smaranjitghose/auto_vaidya pull request #29
Opened 2020-08-23 18:46 UTC by amoghatsunil

2020-08-24 13:25 UTC, smaranjitghose commented
> _No description provided._

Please checkout the guidelines for PR, I gave in the issues
I was expecting a link to preview the Jupyter Notebook in Google Colab and more description on the PR, about your findings, performance metrics used, what did you use to decide the best model, different algos used

2020-08-25 16:07 UTC, amoghatsunil commented
@smaranjitghose 
i have added link to the notebook in google colab

2020-08-28 11:53 UTC, smaranjitghose commented
> @smaranjitghose
> i have added link to the notebook in google colab

Please only give the best model weights in the PR, the rest can be inferred from the notebook

2020-08-28 11:54 UTC, smaranjitghose commented on diabetes_pred/Models/readme
> +
Not Required
The notebook is self explanatory

2020-08-28 11:54 UTC, smaranjitghose commented on diabetes_pred/readme
> +auc 0.6750868751670676
Not Required! The notebook is self explanatory

2020-08-28 11:55 UTC, smaranjitghose requested changes

2020-08-28 11:55 UTC, smaranjitghose commented on diabetes_pred/readme
> +{'clf__C': 1000.0, 'clf__gamma': 0.001, 'clf__kernel': 'rbf'}
Always give the comparative analysis in a table

2020-09-21 16:23 UTC, closed without merging