Added contributing.md file
smaranjitghose/auto_vaidya pull request #45
Opened 2020-09-05 11:10 UTC by shraddhavp

added the contributing.md file closes issue #40

2020-09-05 11:13 UTC, shraddhavp commented
@anushbhatia  sir  created PR for contributing.md file please  check it and let me know for any changes

2020-09-06 04:54 UTC, anushbhatia commented on CONTRIBUTING.md
> +#Contributing
add space between # and contribution

2020-09-06 04:57 UTC, anushbhatia requested changes

2020-09-06 04:57 UTC, anushbhatia commented on CONTRIBUTING.md
> +##Code of Conduct
we already have code of conduct for this

2020-09-06 04:57 UTC, anushbhatia commented on CONTRIBUTING.md
> +## Pull Request process
https://github.com/smaranjitghose/girlscript_chennai_website/blob/master/CONTRIBUTING.md
add code snippets to the file.
Grading sheet
you  can add gif's too

2020-09-06 04:57 UTC, anushbhatia commented on CONTRIBUTING.md
> +### Our Standards
isn't this part of code of conduct why should we mention this in our contribute.md

2020-09-06 04:57 UTC, anushbhatia commented on CONTRIBUTING.md
> +This Code of Conduct applies both within project spaces and in public spaces when an individual is representing the project or its community. Examples of representing a project or community include u
this is not code of conduct please take care and rectify this file

2020-09-06 11:11 UTC, shraddhavp commented
ok I will do it

2020-09-06 11:13 UTC, closed without merging